stages:
  - build

variables:
    CI_DOCKER_REGISTRY: "ciregistry.espressif.cn:8443"
    ESP_THREAD_BR_PATH: "$CI_PROJECT_DIR"

pre_commit:
  stage: .pre
  image: "$CI_DOCKER_REGISTRY/esp-idf-pre-commit:1"
  script:
    - cd ${ESP_THREAD_BR_PATH}
    - apt-get update && apt-get install -y clang-format-11
    - git fetch origin main
    - git diff-tree --no-commit-id --name-only -r HEAD origin/main | xargs pre-commit run --files

.submodule_update: &submodule_update
  - cd $ESP_THREAD_BR_PATH
  - git submodule update --init --recursive

.build_basic_thread_border_router: &build_basic_thread_border_router
  - cd $IDF_PATH/examples/openthread/ot_rcp
  - idf.py --preview set-target esp32h2
  - idf.py build
  - cd $ESP_THREAD_BR_PATH/examples/basic_thread_border_router
  - idf.py set-target esp32
  - idf.py build
  - idf.py set-target esp32c3
  - idf.py build
  - idf.py set-target esp32s3
  - idf.py build

build_examples:
    stage: build
    image: espressif/idf:latest
    script:
        - *submodule_update
        - *build_basic_thread_border_router

