stages:
  - build

variables:
    ESP_IDF_PATH: "$CI_PROJECT_DIR/esp-idf"
    ESP_THREAD_BR_PATH: "$CI_PROJECT_DIR"

.submodule_update: &submodule_update
  - cd $ESP_THREAD_BR_PATH
  - git submodule update --init --recursive

.setup_idf: &setup_idf
  - cd $CI_PROJECT_DIR
  - git clone --recursive --single-branch -b master https://github.com/espressif/esp-idf.git
  - cd $ESP_IDF_PATH
  - ./install.sh
  - . ./export.sh

.build_basic_thread_border_router: &build_basic_thread_border_router
  - cd $ESP_IDF_PATH/examples/openthread/ot_rcp
  - idf.py --preview set-target esp32h2
  - idf.py build
  - cd $ESP_THREAD_BR_PATH/examples/basic_thread_border_router
  - idf.py set-target esp32
  - idf.py build
  - idf.py set-target esp32c3
  - idf.py build
  - idf.py set-target esp32s3
  - idf.py build

build_examples:
    stage: build
    image: $CI_DOCKER_REGISTRY/esp-env-v5.0:2
    script:
        - *setup_idf
        - *submodule_update
        - *build_basic_thread_border_router

