stages:
  - build
  - docs

variables:
    CI_DOCKER_REGISTRY: "ciregistry.espressif.cn:8443"
    ESP_THREAD_BR_PATH: "$CI_PROJECT_DIR"

pre_commit:
  stage: .pre
  image: "$CI_DOCKER_REGISTRY/esp-idf-pre-commit:1"
  script:
    - cd ${ESP_THREAD_BR_PATH}
    - apt-get update && apt-get install -y clang-format-11
    - git fetch origin main
    - git diff-tree --no-commit-id --name-only -r HEAD origin/main | xargs pre-commit run --files

.submodule_update: &submodule_update
  - cd $ESP_THREAD_BR_PATH
  - git submodule update --init --recursive

.build_basic_thread_border_router: &build_basic_thread_border_router
  - cd $IDF_PATH/examples/openthread/ot_rcp

  # Change 'esp32h2' to 'esp32h4' (becasue esp-idf change it)
  # To do: Change 'esp32h4' to 'esp32h2' after target 'esp32h2' is added in esp-idf
  - idf.py --preview set-target esp32h4

  - idf.py build
  - cd $ESP_THREAD_BR_PATH/examples/basic_thread_border_router
  - idf.py set-target esp32
  - idf.py build
  - idf.py set-target esp32c3
  - idf.py build
  - idf.py set-target esp32s3
  - idf.py build

build_examples:
    stage: build
    image: espressif/idf:latest
    script:
        - *submodule_update
        - *build_basic_thread_border_router

build_docs:
    stage: docs
    image: $CI_DOCKER_REGISTRY/esp-idf-doc-env-v5.0:2-3
    variables:
        ESP_DOCS_LATEST_BRANCH_NAME: "main"
    artifacts:
        when: always
        paths:
            - docs/_build/*/*/*.txt
            - docs/_build/*/*/html/*
        expire_in: 1 days
    script:
        - cd docs
        - pip install -r requirements.txt
        - build-docs -t esp32 esp32s2 esp32s3 esp32c3 -l en

.deploy_docs_template:
    stage: docs
    image: $CI_DOCKER_REGISTRY/esp-idf-doc-env-v5.0:2-3
    needs:
        - build_docs
    variables:
        ESP_DOCS_LATEST_BRANCH_NAME: "main"
    script:
        - source ${CI_PROJECT_DIR}/docs/utils.sh
        - add_doc_server_ssh_keys $DOCS_DEPLOY_PRIVATEKEY $DOCS_DEPLOY_SERVER $DOCS_DEPLOY_SERVER_USER
        - export GIT_VER=$(git describe --always)
        - pip install -r ${CI_PROJECT_DIR}/docs/requirements.txt
        - deploy-docs

deploy_docs_preview:
    extends:
        - .deploy_docs_template
    variables:
        TYPE: "preview"
        DOCS_BUILD_DIR: "${CI_PROJECT_DIR}/docs/_build/"
        DOCS_DEPLOY_PRIVATEKEY: "$DOCS_PREVIEW_DEPLOY_KEY"
        DOCS_DEPLOY_SERVER: "$DOCS_PREVIEW_SERVER"
        DOCS_DEPLOY_SERVER_USER: "$DOCS_PREVIEW_SERVER_USER"
        DOCS_DEPLOY_PATH: "$DOCS_PREVIEW_PATH"
        DOCS_DEPLOY_URL_BASE: "https://$DOCS_PREVIEW_SERVER_URL/docs/esp-thread-br"

deploy_docs_production:
    extends:
        - .deploy_docs_template
    variables:
        TYPE: "preview"
        DOCS_BUILD_DIR: "${CI_PROJECT_DIR}/docs/_build/"
        DOCS_DEPLOY_PRIVATEKEY: "$DOCS_PROD_DEPLOY_KEY"
        DOCS_DEPLOY_SERVER: "$DOCS_PROD_SERVER"
        DOCS_DEPLOY_SERVER_USER: "$DOCS_PROD_SERVER_USER"
        DOCS_DEPLOY_PATH: "$DOCS_PROD_PATH"
        DOCS_DEPLOY_URL_BASE: "https://docs.espressif.com/projects/esp-thread-br"
